### ISSUE TITLE
Can't be loaded with 3.2 (3221)

### ISSUE THREAD

**Issue by RosaWagner** [simoncozens/SuperTool#11]
Must have come with the last edge version from Glyphs
cc @schriftgestalt

**Comment by etunni** [comment]
Same issue here @schriftgestalt

**Comment by schriftgestalt** [comment]
It seems to be an problem with the signing certificate. I’ll see if I can fix it.

**Comment by gorjious** [comment]
I am on version 3.1.2 (3151). Didn't do any updates or make any changes. Only restarted my machine and got the can't load error.

**Comment by schriftgestalt** [comment]
It seems that there was a problem with the code singing. I re-signed it. Can you please try (best to remove and re-install from the plugin manager)?

**Comment by florianpircher** [comment]
Works for me in 3.2 (3221)

**Comment by gorjious** [comment]
Works for me in 3.1.2 (3151)

**Comment by RosaWagner** [comment]
works for me too, thanks!
