### ISSUE TITLE
Crash with glyph 3.2(3221)

### ISSUE THREAD

**Issue by orioncactus** [simoncozens/SuperTool#12]
I saw the issue solved in #11, but I'm experiencing an issue on macOS 13.3.1, arm64 & macOS 14.0, arm64.

Even after removing all the plugins from `~/Library/Application Support/Glyphs 3` and installing SuperTool, the problem still exists. Additionally, when I install it using the `.glyphsTool` from the `glyph3` branch, the issue still occurs. 

When running it on version 3192, I didn't face this issue.

cc @schriftgestalt 

Update: I tested on Glyphs 3.2(3222), but it has same issue 👀

**Comment by er1chu** [comment]
Wanted to also report that I'm having the same issue, as it has stopped loading with Gylphs with the latest update to macOS.

**Comment by orioncactus** [comment]
Now it works on 3225!
