### ISSUE TITLE
Build as universal binary

### ISSUE THREAD

**Issue by florianpircher** [simoncozens/SuperTool#6]
This would improve (allow?) the usage of the plugin on the new Macs with the M1 system.

Currently, this plugin is x86_64 only:

```bash
SuperTool.glyphsTool (glyphs3) $ file Contents/MacOS/SuperTool 
Contents/MacOS/SuperTool: Mach-O 64-bit bundle x86_64
```

This is what the output of `file` should look like:

```bash
Close Window.glyphsPlugin (main) $ file Contents/MacOS/Close\ Window 
Contents/MacOS/Close Window: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64] [arm64:Mach-O 64-bit bundle arm64]
Contents/MacOS/Close Window (for architecture x86_64):	Mach-O 64-bit bundle x86_64
Contents/MacOS/Close Window (for architecture arm64):	Mach-O 64-bit bundle arm64
```

You should get such a binary with a recent Xcode and then _Product_ → _Archive_ and then _Distribute Content_ → _Build Products_ → _Next_ → _Export_.

***

Great to see SuperTool on Glyphs 3, thank you!

**Comment by simoncozens** [comment]
I think I may be shipping a debug instead of a release binary...

**Comment by simoncozens** [comment]
I don't have an M1 - if you have one, could you try installing there?

**Comment by florianpircher** [comment]
I also have no M1 hardware, but I do distribute some plugins with the method mentioned above of which I do know that they work on M1 Macs.

**Comment by schriftgestalt** [comment]
Doing the steps above, will produce a binary that works on ARM. I just tried.
