### ISSUE TITLE
M1/BigSur+ Compatibility

### ISSUE THREAD

**Issue by eliheuer** [simoncozens/SuperTool#7]
The readme just says:
> The best way to install it is through the Glyphs plugin manager.

But on an M1 Mac Mini running MacOS 11.2, SuperTool doesn't show up in the Plugin Manager, tested on both Glyphs 3.0.2 (standard version as of today), and Glyphs 3.0.3 (cutting edge version).
<img width="866" alt="SuperToolTest-001" src="https://user-images.githubusercontent.com/5162664/121967778-d5d62f80-cd25-11eb-8224-250f7ef782b7.png">

A search for SuperTool does show one result when searching for scripts. The scripts only work in Glyphs 3.0.3 without messing with system Pythons, which can be difficult and confusing. Glyphs 3.0.3 just uses the Python I have installed with Homebrew with no extra work needed from me.
<img width="866" alt="SuperToolTest-002" src="https://user-images.githubusercontent.com/5162664/121968324-fa7ed700-cd26-11eb-841e-106593da8eaa.png">
<img width="864" alt="SuperToolTest-003" src="https://user-images.githubusercontent.com/5162664/121969669-a0334580-cd29-11eb-80b4-6d26e16a976a.png">

**Comment by florianpircher** [comment]
You have the _Installed_ tab selected, select the _All_ tab located in the top left of the Plugin Manager window to also search for plugins that are not currently installed:

<img width="912" alt src="https://user-images.githubusercontent.com/3776198/121973075-cfbf6d80-cd7c-11eb-8acb-8f73ea55de8c.png">

For M1 specifically, I think that https://github.com/simoncozens/SuperTool/issues/6 needs to be resolved first. Then the package index can be updated to offer the plugin to M1 machines, too. (The plugin is currently marked as [restricted to Intel architectures](https://github.com/schriftgestalt/glyphs-packages/blob/glyphs3/packages.plist#L1858-L1860).)

**Comment by eliheuer** [comment]
I tried all the tabs before, including all, and got nothing, see the screenshot below:

<img width="1183" alt="supertool-005" src="https://user-images.githubusercontent.com/5162664/121980501-e516a680-cd40-11eb-9f1d-d6a5e005412b.png">

**Comment by schriftgestalt** [comment]
Super tool is disabled for ARM macs in the packages file, until we have a proper build for it.

**Comment by simoncozens** [comment]
Ah! I think we do have one now, so I’ll PR the packages file.

**Comment by simoncozens** [comment]
Done now!
