### ISSUE TITLE
Crash with Glyphs 3.2

### ISSUE THREAD

**Issue by RosaWagner** [simoncozens/SuperTool#9]
Makes glyphsApp crashing when trying to balance handles. @simoncozens Do you want the crash report by mail?

**Comment by schriftgestalt** [comment]
The code is most likely fixed. It needs a new build.

**Comment by schriftgestalt** [comment]
The code is most likely fixed. It needs a new build.

**Comment by simoncozens** [comment]
I recompiled and pushed the latest build but it's been so long since I did so that I'm not sure I've got it right. Please test!

**Comment by gorjious** [comment]
SuperTool suddenly crashed for me and now it won't let me reinstall 
<img width="532" alt="Screenshot 2023-03-27 at 17 38 16" src="https://user-images.githubusercontent.com/23149420/228090932-cc73b3be-9601-448f-905a-26e11dc598b0.png">

I upgraded to 3.2 (3182) but same message after uninstalling/reinstalling.

**Comment by simoncozens** [comment]
OK, I probably used the wrong signing certificate.

**Comment by RosaWagner** [comment]
To confirm, I have the same:
<img width="263" alt="Capture d’écran 2023-03-28 à 11 14 08" src="https://user-images.githubusercontent.com/12222436/228230888-90974ee2-c951-481f-951d-bdd0a37136fb.png">

**Comment by simoncozens** [comment]
Oh, that's a more interesting error. I'll make sure it's compiling for M1 as well.

**Comment by etunni** [comment]
Stopped in G3 Version: 3.1.2 (3151) / MacOS Catalina 10.15.7
All modules upgraded.
![Screen Shot 2023-03-28 at 16 28 05](https://user-images.githubusercontent.com/5973399/228349692-b6d62bf4-90b9-4547-8d19-5a8c92ac10b4.png)

**Comment by orioncactus** [comment]
I have the same issue too on arm64, 13.2.1(22D68):
<img width="372" alt="스크린샷 2023-03-29 오전 10 55 52" src="https://user-images.githubusercontent.com/7247848/228406297-89d08b94-a344-4b2b-a311-50ff9724d951.png">

**Comment by simoncozens** [comment]
I understand that there is an issue. :-) I shall work on it today.

**Comment by simoncozens** [comment]
I think I have fixed it now.

**Comment by BlessedPrint** [comment]
I have just reinstalled, but got the same error.

**Comment by orioncactus** [comment]
It works fine now :)

I removed `~/Library/Application Support/Glyphs 3/Plugins/SuperTool.glyphsTool` and `~/Library/Application Support/Glyphs 3/Repositories/SuperTool` and reinstalled SuperTools from the Plugin Manager.

**Comment by BlessedPrint** [comment]
Unfortunately I was not so lucky

**Comment by schriftgestalt** [comment]
@simoncozens can you call me?

**Comment by BlessedPrint** [comment]
Can you please give me more details on how to reinstall it so it work again? Unfortunately it doesn't work for me. Thanks.

**Comment by RosaWagner** [comment]
Works for me.
@BlessedPrint you would have to delete it completely from the directory: Script > open script folder > repositories, delete supertool, restart app, reinstall plugin, boom.

**Comment by schriftgestalt** [comment]
What processor is in your mac (intel or arm)?

**Comment by jpt** [comment]
Working for me on Intel macOS 12.6.1

**Comment by metzcreations** [comment]
I'm still having issues after deleting from the directory and re-installing, restarting etc. M1 Macbook Air – macOS 13.2.1

**Comment by schriftgestalt** [comment]
I have spoken with Simon that I'll do the binaries from now on. I'll upload a new version.

**Comment by schriftgestalt** [comment]
I just uploaded a new versions. It works on all my machines. 
Remove and re-install to make sure you get the new version.

**Comment by 113theavenues** [comment]
Is this error related as I now can't load Supertool and it was fine a few days ago.
<img width="402" alt="screenerror" src="https://github.com/simoncozens/SuperTool/assets/88512084/70a69413-dd34-4532-8d0f-ac1e43534271">

**Comment by 113theavenues** [comment]
> Is this error related as I now can't load Supertool and it was fine a few days ago. <img alt="screenerror" width="402" src="https://user-images.githubusercontent.com/88512084/273272731-70a69413-dd34-4532-8d0f-ac1e43534271.png">

I have already tried to uninstall and reinstall but its the same result

**Comment by florianpircher** [comment]
This issue is tracked here:

https://github.com/simoncozens/SuperTool/issues/11
